#!/bin/bash

if [ -z $1 ]; then
  echo "Аddress is еmpty" 
  exit 
fi

zzz=`echo $1|grep -E '^.+(\.{2,}).+$'|wc -l`
if [ $zzz -ne 0 ]; then
   echo "$1 is wrong address"
   exit
fi

nn1=`echo $1|grep -E '^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$'|wc -l`
if [ $nn1 -ne 0 ]; then
    n=`less /opt/zimbra/conf/sender_access_list|grep ^$1|wc -l`
    n_n=`less /opt/zimbra/conf/sender_access_list|grep ^$1`
    if [ $n -eq 0 ]; then
	su -l zimbra -c "echo \"$1	REJECT\" >> /opt/zimbra/conf/sender_access_list"
        su -l zimbra -c "/opt/zimbra/postfix/sbin/postmap /opt/zimbra/conf/sender_access_list"
	#   su -l zimbra -c 'postfix reload'
	echo "E-mail address $1 is added in the black list"
	exit
    else
	echo "<font color='red'> E-mail address $1 already exists in the list</font><br> $n_n"
	exit
    fi
fi


nn2=`echo $1|grep -E '([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,10})$'|grep -E '[a-zA-Z]+'|wc -l`
if [ $nn2 -ne 0 ]; then
  n=`less /opt/zimbra/conf/sender_access_list|grep ^$1|wc -l`
  if [ $n -eq 0 ]; then
    su -l zimbra -c "echo \"$1	REJECT\" >> /opt/zimbra/conf/sender_access_list"
    su -l zimbra -c "/opt/zimbra/postfix/sbin/postmap /opt/zimbra/conf/sender_access_list"
#    su -l zimbra -c 'postfix reload'
    echo "E-mail domain $1 is added in the black list"
    exit
  else
    echo "<font color='red'> E-mail domain $1 already exists in the list</font><br> $n_n"
    exit
  fi
fi 


if [ $nn1 -eq 0 ] && [ $nn2 -eq 0 ]; then

  nn=`echo $1|grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'|wc -l`
  n_n=`less /opt/zimbra/conf/sender_access_list|grep ^$1`

  if [ $nn -eq 0 ]; then
   echo "$1 is wrong address"
   exit
  fi

  
  n1=`echo $1|cut -d '.' -f 1`
  if [ $n1 -gt 254 ]; then
     nn=0
  fi

  if [ $n1 -eq 0 ]; then
     nn=0
  fi

  n2=`echo $1|cut -d '.' -f 2`
  if [ $n2 -gt 254 ]; then
     nn=0
  fi

  n3=`echo $1|cut -d '.' -f 3`
  if [ $n3 -gt 254 ]; then
     nn=0 
  fi

  n4=`echo $1|cut -d '.' -f 4`
  if [ $n4 -gt 254 ]; then
     nn=0
  fi

  if [ $n4 -eq 0 ]; then
     nn=0
  fi


  if [ $nn -eq 0 ]; then
   echo "$1 is wrong address"
   exit
  fi

fi


n=`less /opt/zimbra/conf/sender_access_list|grep ^$1|wc -l`
n_n=`less /opt/zimbra/conf/sender_access_list|grep ^$1`
if [ $n -eq 0 ]; then
   su -l zimbra -c "echo \"$1	REJECT\" >> /opt/zimbra/conf/sender_access_list"
   su -l zimbra -c "/opt/zimbra/postfix/sbin/postmap /opt/zimbra/conf/sender_access_list"
#   su -l zimbra -c 'postfix reload'
   echo "IP address $1 is added in the white list"
else
   echo "<font color='red'>IP address $1 has already been in the list</font><br> $n_n"
fi

